### ISSUE TITLE
Add links for team members

### ISSUE THREAD

**Issue by zmknox** [Lovely-Development-Team/tildy.dev#5]
Some team members' names don't yet link to anything. We should add links to them!

- [x] Alex
- [ ] Ben
- [ ] Brian
- [ ] David
- [ ] Dom
- [ ] Ellen
- [x] Izzy
- [ ] Kirk
- [x] Madi
- [x] Majd
- [x] Matt C
- [x] Matt V

**Comment by RosemaryOrchard** [comment]
If everyone just does a PR for their website, or asks someone to do it for them that will be best!
